services:
  mysql:
    image: mysql
    container_name: curlingseattle9-db
    restart: unless-stopped
    tty: true
    ports:
      - "${GCC_MYSQL_PORT:-3306}:3306"
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - ./.docker/db-load:/docker-entrypoint-initdb.d
      - mysqldata9:/var/lib/mysql
      
  drupal:
    image: drupal:latest
    container_name: drupal9-next
    working_dir: /opt/drupal/web
    ports:
      - "${GCC_DRUPAL_PORT:-8999}:80"
    env_file:
      - .env
    volumes:
      - ./drupalwebroot:/opt/drupal/web
      - ./.docker/drupal.ini:/usr/local/etc/php/conf.d/drupal.ini
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysqldata9: